config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
  resources :skills
  
  get 'pages/home'
  get 'pages/events'
  get 'pages/talent'
  post 'users/add_skill'
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true 

  has_and_belongs_to_many :skills

  def self.search(search)

    
    find_by_sql("SELECT DISTINCT users.* FROM users
    INNER JOIN skills_users ON users.id = skills_users.user_id 
    INNER JOIN skills ON skills_users.skill_id = skills.id
    WHERE users.name @@ '%#{search}%' OR users.description @@ '%#{search}%' OR skills.name @@ '%#{search}%'
    OR users.email @@ '%#{search}%' OR users.title @@ '%#{search}%' OR users.organization @@ '%#{search}%'") 

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :title, :organization, :description, :display_phone, :area_code, :prefix, :line_number, :mentor ])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email, :password, :password_confirmation])
      
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def events
  end

  def talent
    @users = User.paginate(:page => params[:page], :per_page => 10)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def edit
    @skills = @user.skills.order(:created_at)
    @skill = Skill.new
    super
  end
  
    protected
    
    def after_sign_up_path_for(users)
      edit_user_registration_path
    end

    def update_resource(resource, params)
      resource.update_without_password(params)
    end

end
 

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

    def create 
      @skill = Skill.find(params[:select_tag])
      
      @user = current_user
      @user.skills << @skill
      
      @skill.save!
      
      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end
  
    end

    

    def add_skill_params
        params.require(:skill).permit(:name)
    end

    def show
      @skill = Skill.find(params[:id])
    end
    
    def destroy
      @skill = Skill.find(params[:id])

      current_user.skills.destroy(params[:id])

      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end
    end


    def add_skill
      @skill = Skill.find(params[:id])
      
      ActiveRecord::Base.connection.execute("INSERT INTO skills_users ('skill_id', 'user_id') VALUES ('%#{@skill.id}%', '%#{current_user.id}%')")
      
      @skill.save!
      
      respond_to do |format|
        format.html { redirect_to edit_user_registration_path }
        format.js
      end

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @skills = @user.skills
  end

  def update 
    @user = User.find(current_user.id)

    if @user.update_attributes(update_user_params)
      render "pages/home"
    else
      render 'edit'
    end
  end

  def update_user_params
    params.require(:user).permit(:name, :description, :area_code, :prefix, :line_number)
  end

  def index 
    if params[:search].blank?
      @users = User.all()
    else
      @users = User.all()
      @users = User.search(params[:search])
      params.delete :search
    end
  end

  skip_before_action :verify_authenticity_token 
  def add_skill

    @skill = Skill.find(params[:select_tag])
    
    @user = current_user
    @user.skills << @skill
    #@user.update_attribute :skill_ids << @skill.id
    #ActiveRecord::Base.connection.execute("INSERT INTO skills_users ('skill_id', 'user_id') VALUES ('%#{@skill.id}%', '%#{current_user.id}%')")
    
    @skill.save!
    
    respond_to do |format|
      format.html { redirect_to edit_user_registration_path }
      format.js
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navPartial.html.erb
<div class="nav">
    <div id = "navbar">
      <div class="nav-button"> <%= link_to "Home", pages_home_path %> </div>
      <div class="nav-button"> <%= link_to "Events", pages_events_path %> </div>
      <div class="nav-button"> <%= link_to "Talent", users_path %> </div>


      <% if user_signed_in? %>
        <div class = "nav-button" id="profile-button"> <%= link_to current_user.email, edit_user_registration_path %> </div>
        <div class = "nav-button" id="log-button"> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </div>
      <%else%>
        <div class="nav-button" id="profile-button"> <%= link_to "Sign_up", new_user_registration_path %> </div>
        <div class="nav-button" id="log-button"> <%= link_to "Sign_in", new_user_session_path %> </div>
      <%end%>
    </div>
  </div>
 <body>
  <div class = "main">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>
  </body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
    <title>SoeDev</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: "only screen and (min-width: 401px)", 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
   
 <%= render "layouts/navPartial"%>
 
  <body>
    <div class = "main">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/events.html.erb
<h1>Events</h1>

<iframe src="https://calendar.google.com/calendar/embed?src=clemboarder13%40gmail.com&ctz=America/New_York" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>

app/views/pages/home.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/pages/talent.html.erb
<h1>Talent</h1>

<%= will_paginate @users %>

app/views/skills/_addSkillForm.html.erb
  <%= form_for @skill, :url => { :action => "create", :controller => "skills"} do |f|%>

      <%= f.label "Skill Name" %>
      <%= f.text_field (:name) %>

      <%= f.submit ("Add this skill")%>
      
  <%end%>

app/views/skills/_skill.html.erb
<li id = "skill_item_<%=skill.id%>">
    <%= skill.name %>
    <%= link_to "remove", skill, method: :delete, remote: true  %>
</li>

app/views/skills/_skills.html.erb
  <% @skills = @user.skills%>
  <% @skills.each do |c| %>
    <li></li>
    <div id="skillBox"><%= c.name %></div>
  <% end %>

app/views/skills/add_skill.js.erb
$('#skillsList').append("<%= j render @skill %>");

app/views/skills/create.js.erb
$('#skillsList').append("<%= j render @skill %>");

app/views/skills/destroy.js.erb
$("#skill_item_<%= @skill.id%>").remove();

app/views/users/add_skill.js.erb
$('#skillList').append("<%= j render @skill %>")

app/views/users/index.html.erb
    <div id="form">
    <%= form_tag users_path, method: :get, id: "search-form" do %>
        <%= label_tag :q, "Lets narrow It down" %>
        <%= text_field :search, params[:search], id: "search-field" %>
        <%= submit_tag "Search", id: "search-button" %>
    <% end %>
</div>
<br>

<div class ="content">

    <% if @users.empty? %>
        <div id="noUsersMatch"><h1>Sorry, there doesn't seem to be anyone that matches that query.</h1></div>
    <% else %>
        <% @users.each do |c| %>
            <%= link_to user_path(c.id) do %>
                <div id="userResult">
                    <div id="userName"><h2><%= c.name %></h2></br><p id="email"><%= c.email %></p></div>
                    <div id="userDesc"><p><%= c.description %></p></div>
                </div>
            <%end%> 
        <% end %>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="profile">
	<div id="profile-photo"><img src="http://www.funnyjunksite.com/pictures/wp-content/uploads/2012/08/Strange-Cat.jpg">
	</div> 
<div id="profile info" style="padding-top: 20px; padding-left: 10px;">
	<div id ="name"><%=@user.name %>
	</div>
	<div id ="contact">
	<% if @user.display_phone %>
    (<%= @user.area_code %>) <%= @user.prefix %> - <%= @user.line_number %>
	<br>
	<% end %>
	<%=@user.email %>
</div>

<br>
<%=@user.description %> 
</div>




<% if @user.mentor %>
    <h1>Message me about being a mentor</h1>
<%end%>

<% @skills.each do |c| %>
    <p><%= c.name%></p>
<%end%>
</div>